//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Config {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Config() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Infrastructure.Resources.Config", typeof(Config).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact@flow.com.
        /// </summary>
        public static string SwaggerContactEmail {
            get {
                return ResourceManager.GetString("SwaggerContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow.
        /// </summary>
        public static string SwaggerContactName {
            get {
                return ResourceManager.GetString("SwaggerContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://flow.com/contact.
        /// </summary>
        public static string SwaggerContactUri {
            get {
                return ResourceManager.GetString("SwaggerContactUri", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status/401.
        /// </summary>
        public static string HttpResponseErrorTypeStatus401Unauthorized {
            get {
                return ResourceManager.GetString("HttpResponseErrorTypeStatus401Unauthorized", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status/404.
        /// </summary>
        public static string HttpResponseErrorTypeStatus404NotFound {
            get {
                return ResourceManager.GetString("HttpResponseErrorTypeStatus404NotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status/500.
        /// </summary>
        public static string HttpResponseErrorTypeStatus500InternalServerError {
            get {
                return ResourceManager.GetString("HttpResponseErrorTypeStatus500InternalServerError", resourceCulture);
            }
        }        
    }
}
