version: '3.9'

services:
  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
    volumes:
      - ./data/seq-data:/usr/share/seq/data
    networks:
      - flow-network


  # elasticsearch:
  #   image: elasticsearch:7.9.2
  #   container_name: elasticsearch
  #   environment:
  #     - http.host=0.0.0.0
  #     - transport.host=localhost  # Correção: evitar conflitos de transporte
  #     - xpack.security.enabled=false
  #     - xpack.monitoring.enabled=false
  #     - cluster.name=elasticsearch
  #     - bootstrap.memory_lock=true
  #     - discovery.type=single-node
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #     - "cluster.routing.allocation.disk.threshold_enabled=false"
  #     - "indices.recovery.max_concurrent_operations=4"
  #     - "indices.recovery.max_concurrent_file_chunks=2"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #     nofile: 65536      
  #   ports:
  #     - "9200:9200"
  #   volumes:
  #       - ./data/elasticsearch-data:/usr/share/elasticsearch/data
  #       - ./data/elasticsearch-logs:/usr/share/elasticsearch/logs
  #   networks:
  #     - flow-network
  #   depends_on:
  #     - flowapi

  # kibana:
  #   image: kibana:7.9.2
  #   container_name: kibana
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #   ports:
  #     - "5601:5601"
  #   depends_on:
  #     - flowapi
  #   networks:
  #     - flow-network

  mssql:
    container_name: mssqlserver
    hostname: mssql-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'SqlServer@db'
      MSSQL_DATA_DIR: /usr/share/mssql/data
      MSSQL_PID: 'Developer' 
      MSSQL_TCP_PORT: 1433 
    ports: 
      - "1433:1433"
    volumes:
      - ./data/mssql-data:/usr/share/mssql/data
      - ./data/mssql-log-data:/usr/share/mssql/log
      - ./data/mssql-secrets-data:/usr/share/mssql/secrets
    networks:
      - flow-network
    
  flowapi:
     container_name: flowapi
     hostname: flowapi
     image: flowapi:latest
     build:
       context: ../../
       dockerfile: Apis/Application/Dockerfile
     environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_HTTP_PORTS=8080
       - ASPNETCORE_HTTPS_PORTS=8081
       - DOTNET_RUNNING_IN_CONTAINER=true
       - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
     ports:
       - "5122:5122"
       - "7282:7282"
     volumes:
        - ./data/flowapi-data:/usr/share/flowapi/data
        - ./data/flowapi-logs:/usr/share/flowapi/logs
     networks:
       - flow-network
     depends_on:
        - mssql
        - seq
     deploy:
       resources:
         limits:
           cpus: '1'
           memory: 1G    

volumes:
   elasticsearch-data:
      driver: local
   elasticsearch-logs:
      driver: local
   mssql-data:
      driver: local
   mssql-log-data:
      driver: local
   mssql-secrets-data:
      driver: local
   seq-data:
      driver: local
   flowapi-data:
      driver: local
   flowapi-logs:
      driver: local

networks:
  flow-network:
    driver: bridge